import React, { useMemo, useState } from 'react';
import { ArrowDown, ArrowUp, Boxes, CircleDot, PackageCheck, Search, ShoppingCart } from 'lucide-react';
import { NoonOrder, PurchaseInvoice, SaleInvoice, SerialItem, StockTransfer, WeeklyInventoryCount } from '../types';
import { formatCurrency } from '../utils/helpers';

interface Props { serials: SerialItem[]; products: any[]; purchaseInvoices: PurchaseInvoice[]; saleInvoices: SaleInvoice[]; stockTransfers: StockTransfer[]; weeklyInventoryCounts: WeeklyInventoryCount[]; noonOrders: NoonOrder[]; }
type Event = { id:string; date:string; title:string; description:string; icon:React.ReactNode; tone:string };

export default function SerialTimeline({ serials, products, purchaseInvoices, saleInvoices, stockTransfers, weeklyInventoryCounts, noonOrders }: Props) {
 const [search,setSearch]=useState(''); const [selectedId,setSelectedId]=useState('');
 const suggestions=useMemo(()=>{const q=search.trim().toLowerCase(); if(!q)return serials.slice(0,8); return serials.filter(s=>[s.serial,s.imei1,s.imei2,s.productName].filter(Boolean).some(v=>String(v).toLowerCase().includes(q))).slice(0,10)},[search,serials]);
 const selected=serials.find(s=>s.id===selectedId) || (suggestions.length===1?suggestions[0]:null);
 const events=useMemo<Event[]>(()=>{ if(!selected)return []; const ev:Event[]=[];
   const p=selected.purchaseInvoiceId?purchaseInvoices.find(x=>x.id===selected.purchaseInvoiceId):undefined; if(p) ev.push({id:'p',date:p.date,title:'دخول من فاتورة شراء',description:`${p.invoiceNumber} • ${p.supplierName} • ${formatCurrency(selected.costPrice)}`,icon:<ArrowDown size={15}/>,tone:'text-emerald-300'});
   const transferHits=stockTransfers.filter(t=>t.items.some(i=>(i.serials||[]).some(s=>s.serial===selected.serial))).sort((a,b)=>a.date.localeCompare(b.date)); transferHits.forEach(t=>ev.push({id:`t-${t.id}`,date:t.date,title:'تحويل مخزون',description:`${t.transferNumber} • ${t.fromLocation} → ${t.toLocation}`,icon:<Boxes size={15}/>,tone:'text-blue-300'}));
   weeklyInventoryCounts.forEach(c=>c.lines.filter(l=>l.productId===selected.productId).forEach(l=>ev.push({id:`c-${c.id}`,date:c.endDate,title:'جرد',description:`النظري ${l.theoreticalQty} • الفعلي ${l.physicalQty} • الفرق ${l.difference}`,icon:<PackageCheck size={15}/>,tone:l.difference===0?'text-emerald-300':'text-orange-300'})));
   const s=saleInvoices.find(x=>x.id===selected.saleInvoiceId); if(s) ev.push({id:'s',date:s.date,title:'بيع وخروج من المخزون',description:`${s.invoiceNumber} • ${s.customerName} • ${formatCurrency(selected.salePrice||0)}`,icon:<ArrowUp size={15}/>,tone:'text-red-300'});
   const no=selected.noonOrderId?noonOrders.find(x=>x.id===selected.noonOrderId):undefined; if(no) ev.push({id:'n',date:no.date,title:'ربط بأوردر منصة',description:`${no.platform} • ${no.orderNumber}`,icon:<ShoppingCart size={15}/>,tone:'text-violet-300'});
   ev.push({id:'created',date:selected.createdAt.slice(0,10),title:'إنشاء السيريال في النظام',description:`الحالة الحالية: ${selected.status} • المكان: ${selected.location||'—'}`,icon:<CircleDot size={15}/>,tone:'text-muted'});
   return ev.sort((a,b)=>b.date.localeCompare(a.date)); },[selected,purchaseInvoices,saleInvoices,stockTransfers,weeklyInventoryCounts,noonOrders]);
 return <div className="space-y-4">
   <div><h2 className="text-lg font-bold text-white">Serial Timeline — رحلة السيريال</h2><p className="text-xs text-muted mt-1">من أول دخول الجهاز للنظام لحد آخر حركة عليه.</p></div>
   <div className="card p-3"><div className="relative"><Search size={16} className="absolute right-3 top-3 text-muted"/><input value={search} onChange={e=>{setSearch(e.target.value); if(!selectedId)setSelectedId('')}} placeholder="امسح/اكتب Serial أو IMEI" className="input-dark w-full pr-9"/></div>{search&&<div className="mt-2 space-y-1">{suggestions.map(s=><button key={s.id} onClick={()=>{setSelectedId(s.id);setSearch(s.serial)}} className={`w-full text-right p-2 rounded-lg ${s.id===selectedId?'bg-violet-900/30':'hover:bg-white/5'}`}><div className="font-mono text-sm">{s.serial}</div><div className="text-xs text-muted">{s.productName} • {s.status}</div></button>)}</div>}</div>
   {selected ? <div className="grid lg:grid-cols-[280px,1fr] gap-4"><div className="card p-4 space-y-3"><div className="text-xs text-muted">الجهاز</div><div className="font-bold">{selected.productName}</div><div className="font-mono text-violet-300">{selected.serial}</div><div className="text-xs text-muted">IMEI 1: {selected.imei1||'—'}</div><div className="text-xs text-muted">IMEI 2: {selected.imei2||'—'}</div><div className="border-t border-border pt-3 text-sm"><div className="flex justify-between"><span className="text-muted">الحالة</span><span>{selected.status}</span></div><div className="flex justify-between mt-2"><span className="text-muted">التكلفة</span><span>{formatCurrency(selected.costPrice)}</span></div><div className="flex justify-between mt-2"><span className="text-muted">الموقع</span><span>{selected.location||'—'}</span></div></div></div><div className="card p-5"><div className="space-y-5">{events.map((e,i)=><div key={e.id} className="relative flex gap-3"><div className="relative z-10 w-8 h-8 rounded-full bg-elevated border border-border flex items-center justify-center">{e.icon}</div>{i<events.length-1&&<div className="absolute right-[15px] top-8 bottom-[-20px] w-px bg-border"/>}<div className="min-w-0"><div className={`font-semibold ${e.tone}`}>{e.title}</div><div className="text-xs text-muted mt-1">{e.date}</div><div className="text-sm mt-1">{e.description}</div></div></div>)}</div></div></div> : <div className="card p-10 text-center text-muted">ابحث عن Serial أو IMEI لعرض الرحلة كاملة.</div>}
 </div>;
}
